SDL_CFLAGS = -I/usr/x86_64-w64-mingw32/include/SDL2 -Dmain=SDL_main 
SDL_LDFLAGS = -L/usr/x86_64-w64-mingw32/lib -lSDL2_ttf -lSDL2_image -lmingw32 -lSDL2main -lSDL2 -mwindows

CXX=x86_64-w64-mingw32-g++

sdl-graphics: sdl-graphics.o
	$(CXX) sdl-graphics.o $(SDL_LDFLAGS) -o sdl-graphics.exe

sdl-graphics.o: sdl-graphics.cpp
	$(CXX) -c $(SDL_CFLAGS) sdl-graphics.cpp -o sdl-graphics.o

clean: 
	rm sdl-graphics.exe sdl-graphics.o

